### PR TITLE
chore: update docs to make release process clearer

### PR DESCRIPTION
**Pull request by Inksprout**
* Updated Contributing and Release guide to try capture our release process.
* updated release trigger scripts so the repo slug is correctly captured.
@YOU54F This is what I thought the intention is for the current release process, if not please correct me😅

### CODE REVIEW

**Comment by Inksprout** [comment]
Side note: builds won't pass because only markdown files have changed it seems like

**Comment by YOU54F** [comment]
Yes that is correct, great update thanks.  I realised the slug pattern was diff because in some repos I had a https remote rather than an ssh remote, so the git remote command returns a diff value, would be nice to detect that in the script as it took me a while to grok

**Comment by YOU54F** [comment]
I tried to diverge as little as possible away from the original fork, but happy to move this more in line with a standardised build pattern in the future

**Comment by Inksprout** [comment]
> I tried to diverge as little as possible away from the original fork, but happy to move this more in line with a standardised build pattern in the future

yeah I think gradual change is good in this case

**Pull request merged**
