### PR TITLE
feat: Add 'application/vnd.api+json' as allowed type in findApplicationJsonMediaType

### PR DESCRIPTION
**Pull request by ThomasKoppensteiner**
Please use this PR as a starting point for approaching #12.

### CODE REVIEW

**Comment by mefellows** [comment]
Thanks, i'll have this reviewed in the next sprint (2 weeks).

**Comment by ThomasKoppensteiner** [comment]
Any updates on this?

**Comment by mefellows** [comment]
See https://github.com/pactflow/swagger-mock-validator/pull/22, I think it should supersede this.

**Comment by YOU54F** [comment]
Hey @vwong is this PR no longer required, post your changes in #22

**Comment by mefellows** [comment]
Yes, this and #26 would definitely cover this use case. Closing.

**Pull request closed without merging**
